# Generated by Django 3.1.3 on 2020-11-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.CharField(max_length=20)),
                ('dcity', models.CharField(max_length=20)),
                ('acity', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
    ]
