# Generated by Django 3.1.3 on 2020-11-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='arrivalDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='departureDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
