# Generated by Django 3.1.3 on 2020-11-14 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='concernFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateTimeField(null=True)),
                ('arrivalDate', models.DateTimeField(null=True)),
                ('flightNumber', models.CharField(max_length=20)),
                ('dcity', models.CharField(max_length=20)),
                ('acity', models.CharField(max_length=20)),
                ('price', models.IntegerField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('url', models.CharField(max_length=150)),
                ('openid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.wxuser')),
            ],
        ),
    ]
